language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

install:
  - "echo 'No dependencies :)'"

# command to run tests
script:
  - "git submodule init"
  - "git submodule update"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r tests/requirements.txt --use-mirrors"
  - "nosetests"

